# Generated by Django 3.1.8 on 2021-05-07 06:44

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='social_links',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.SocialMediaLink'),
        ),
    ]
